### ISSUE TITLE
Innacurate GWPS Callout [The A330-900 touches down on runway when GWPS Callout is on 10]

### ISSUE THREAD

**Issue by rasyidkrm** [headwindsim/A339X#42]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2022-05-22T11:47:48+00:00",
    "ref": "refs/tags/v0.200",
    "sha": "89b88a85942045ce719bdcd7fd24002e2e0b196c",
    "actor": "Revyn112",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.200"
}
```

### Describe the bug

During Flare Phase after passing 100ft the GWPS callout starts. However, right when the GWPS Callouts mentions 10 the aircraft touches down on the runway. My descend rate is normal at around 100-130 fps. So it should not drop that fast after the 10 GWPS Callout.

### Expected behavior

When the GWPS Callout mentions 10 the Aircraft should still be 10ft AGL and I should still have time before the aircraft touchdown on the runway. 

### Steps to reproduce

1. Set Arrival Data in the MCDU
2. Set Baro (minimums) in the MCDU
3. Enable Approach Phase in the MCDU
4. Enable Approach Autopilot Function
5. Enter the Aircraft into the g/s
6. GWPS activates 2500 ft AGL
7. Disable A/P on 500 ft AGL and initiate manual override for landing
8. GWPS callsout at 10ft and the aircraft touches down at the exact same time. 

### References (optional)

Please check the video showing the issue on #support page in the Headwind Discord Channel using the following link:

https://discord.com/channels/965000103150645258/965031157064413276/995116121525067916

### Additional info (optional)

Some discord user mentions does have the same issue such as Swan#5718. However other discord users mentions that the issue is not present with them such as steph29#4923 and Pallat#3234

### Discord Username (optional)

SuperAmadeus#9013

**Comment by Revyn112** [comment]
Fixed in next stable update
