### ISSUE TITLE
Airborne Traffic Situational Awareness only present on "Arc" not "Rose/Nav" ND setting

### ISSUE THREAD

**Issue by Normolo** [headwindsim/A339X#56]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-03-05T17:45:20+00:00",
    "ref": "refs/heads/main",
    "sha": "81c4db18e77c8b1658e5994f6edeb8056b16f756",
    "actor": "Revyn112",
    "event_name": "manual",
    "pretty_release_name": "main:81c4db18",
    "version": "v0.4.0-dev.81c4db1"
}
```

### Describe the bug

The new Airborne Traffic Situational Awareness system only displays on the "Arc" ND mode and not the "Rose/Nav" ND mode.

### Expected behavior

There will be a discrepancy on the visuals of the ATSA system between the Arc and Nav ND modes.

### Steps to reproduce

1. Setup flight as normal
2. Find traffic
3. Notice the difference that traffic is displayed between the ND modes

### Additional info (optional)

![image](https://user-images.githubusercontent.com/53821637/224107870-9855c46a-dd19-4441-b01d-3e7a229dfae7.png)

### Discord Username (optional)

Cozmo#7825

**Comment by st3ph29** [comment]
https://prnt.sc/L1pfwonfDs4_

**Comment by st3ph29** [comment]
[](https://prnt.sc/L1pfwonfDs4_)

**Comment by st3ph29** [comment]
it does

![téléchargement](https://user-images.githubusercontent.com/72687956/224181689-53523918-c703-4d57-a715-8ef93886fbd5.png)

**Comment by Revyn112** [comment]
This is already implemented.
