### ISSUE TITLE
A330 neo EFB

### ISSUE THREAD

**Issue by boomerc154** [headwindsim/A339X#63]
### Aircraft Version

Stable

### Build info

```json
"built": "2023-05-17T21:42:16+00:00",
    "ref": "refs/tags/v0.4.0",
    "sha": "83307d7c1af2bfb6577770b5b625d140a5112d66",
    "actor": "Revyn112",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.4.0",
    "version": "v0.4.0-rel.83307d7"
```

### Describe the bug

After installing update 0.4.0 today, the EFB will not give the option to update the selected fuel load. 
I mean, the "Instant, Fast, Real" buttons along with the activation arrow are missing.

On the Payload page, it doeas load the plan from Simbrief, but the activation button at the bottom of the page doeas not work once I click it and therefore won't populate.

I had uninstalled and re-installed the Simbridge on both, the FBW A320 and the Headwind A330 as well..

Could you please help?

Thanks!

### Expected behavior

Instructions to correct the issue

### Steps to reproduce

The A330 loads fine once I start MSFS. I even get the notice that Simbridge has connected properly

**Comment by Ithendyr** [comment]
Hi, maybe the problem is solved but i've encountered this issue too.
It happen when the functions Payload and Fuel Synchronization with GSX are enabled. [https://docs.flybywiresim.com/fbw-a32nx/feature-guides/gsxintegration/](url)

**Comment by Revyn112** [comment]
This is intended. A warning hint will be shown in future to make things more clear.
With GSX Sync enabled, the fuel and payload will be handle by GSX.
