### ISSUE TITLE
Max Fuel Capacity

### ISSUE THREAD

**Issue by Uljos** [headwindsim/A339X#65]
### Description

The ‘real’ A330-900 neo has a fuel capacity of approx 111 tons whereby the Headwind A330-900 Neo allows to enter only a max of 99.9 tons on the Init B page. Any chance to adjust this? Thanks

**Comment by st3ph29** [comment]
https://prnt.sc/2wtEdDU6afml

Check your install and update the plane via the installer

**Comment by Uljos** [comment]
Thank you, got it. Was irritated by the layout of the boxes 🔲🔲.🔲    Great Plane, love to fly it!
