### ISSUE TITLE
ND Not working

### ISSUE THREAD

**Issue by briiiicee** [headwindsim/A339X#70]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2023-05-18T21:09:31+00:00",
    "ref": "refs/tags/v0.4.1",
    "sha": "ef3667da67c64651544e054b7534d0e8e8099cf6",
    "actor": "Revyn112",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.4.1",
    "version": "v0.4.1-rel.ef3667d"
}
```

### Describe the bug

When I use the A339 there is no way to turn on the ND, once on ground i thought it was my mistake but i can fly the plane like if the ND was working, the plane follows his route and everything is great, do you have any idea ? (sorry for my english, i'm french)
![Microsoft Flight Simulator Screenshot 2023 08 04 - 20 01 01 57](https://github.com/headwindsim/A339X/assets/141446651/3f698e59-ed9c-4f00-8222-f65ab2eb0343)

### Expected behavior

I expect the ND to work in order to make realistic flights.

### Steps to reproduce

Every time I take this plane.

**Comment by Revyn112** [comment]
As this is not a failure of the code we invite you to come to our community support to get help with the aircraft: 

https://discord.headwindsim.net
